### PR TITLE
New change with implemented  latest escaping/sanitization fixes

### PR DESCRIPTION
**Pull request by codepixar**

### CODE REVIEW

**Comment by cristianraiber** [comment]
@codepixar - it still can not be merged because you didn't get the latest version of fashe-wp.

We have a lot of conflicts that can't be fixed manually.

**Comment by codepixar** [comment]
@cristianraiber - I have downloaded the file after marge #39 

image

**Comment by cristianraiber** [comment]
@codepixar - then it must mean your IDE automatically formats code when you open the file. Look at the number of files/lines changed in your PR. Over 80 files and ~ 4,200 lines of code aded and 5,500 removed. Which is mostly your commit removing our spacing (the one that we worked to create using latest PHPCS & WordPress coding standards).

**Comment by codepixar** [comment]
@cristianraiber  - Please check new PR.

Thanks.

**Pull request closed without merging**
